#!/bin/bash
# update-env.sh - Updates .env file with current Codespace URLs

if [ -n "$CODESPACE_NAME" ] && [ -n "$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN" ]; then
    echo "🔄 Updating .env with current Codespace URLs..."
    
    # Create the dynamic URLs
    BACKEND_URL="https://${CODESPACE_NAME}-3001.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
    FRONTEND_URL="https://${CODESPACE_NAME}-3000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
    STEAM_CALLBACK="https://${CODESPACE_NAME}-3001.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}/api/auth/steam/callback"
    
    # Backup .env file (optional safety measure)
    if [ ! -f .env ]; then
    cp .env.example .env
fi

cp .env .env.backup 2>/dev/null || true
    
    # Create the .env file from scratch
    cat << EOF > .env
# This file was auto-generated by update-env.sh

# Backend Configuration
FLASK_APP=src/app.py
FLASK_DEBUG=True
DATABASE_URL=sqlite:///squadup.db
JWT_SECRET_KEY=your-super-secret-jwt-key # CHANGE THIS!

# Steam API Configuration
STEAM_API_KEY= # ADD YOUR STEAM API KEY HERE
STEAM_CALLBACK_URL=${STEAM_CALLBACK}

# Frontend Configuration
FRONTEND_URL=${FRONTEND_URL}
VITE_BACKEND_URL=${BACKEND_URL}

# Codespaces Configuration
APP_BASE_URL=${BACKEND_URL}
CODESPACE_NAME=${CODESPACE_NAME}
GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
VITE_CODESPACE_NAME=${CODESPACE_NAME}
VITE_GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
EOF
    
    # Verify the updates worked
    if grep -q "$BACKEND_URL" .env; then
        echo "✅ Updated URLs:"
        echo "   Backend: ${BACKEND_URL}"
        echo "   Frontend: ${FRONTEND_URL}"
        echo "   Steam Callback: ${STEAM_CALLBACK}"
        echo "   💾 Backup saved as .env.backup"
    else
        echo "❌ Failed to update .env file"
        exit 1
    fi
else
    echo "⚠️  Not in Codespaces environment - keeping existing URLs"
    echo "   Current CODESPACE_NAME: ${CODESPACE_NAME:-'not set'}"
    echo "   Current GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN: ${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-'not set'}"
fi